### ISSUE TITLE
セットアップ時にswigが無いと言われました

### ISSUE THREAD

**Issue by foojy** [matsulib/mecab-service#2]
NeoLogdのインストールの途中で、以下のようなエラーが出ましたので、
flask-mecabのDockerfile のapt-get にswig を追加したらうまく動きましたので、ご報告いたします。

エラー内容
 unable to execute 'swig': No such file or directory
 error: command 'swig' failed with exit status 1
 Running setup.py clean for mecab-python3
 Failed building wheel for mecab-python3

**Comment by matsulib** [comment]
ご報告ありがとうございます。確認中です。
